### ISSUE TITLE
Mentorship Idea: Build Workflow Process for CHAOSS Diversity & Inclusion Badging

### ISSUE THREAD

**Issue by Nebrethar** [badging/diversity-and-inclusion#1]
# About the Project

The CHAOSS Diversity and Inclusion Badging Program began as a way to ensure that D&I metrics can have significant impact in the ways that communities function. The program was created to encourage projects and events towards positive diversity & inclusion practices. The goal of the Diversity & Inclusion Badging Program is to encourage projects and events to obtain D&I badges for reasons of pride, leadership, self-reflection, and self-improvement on issues critical to building the inclusive communities.

The primary goals of the Diversity & Inclusion Badging Program include:

 - Establishing an environment where projects and events can engage in the D&I badging program
 - Aligning the badging program with best practices, guidelines, and recommendations from Diversity & Inclusion efforts on the CHAOSS project
 - Connecting with existing badging standards of IMS Global including building an open peer-review system for the D&I Badging Program.

The aim of this project regards all of these goals, and the work will help the entire Diversity & Inclusion Badging Program. The volunteer for this project will assist in creating a badge submission workflow and peer-review system for the badging process.

* _Difficulty:_ Medium
* _Requirements:_ Extensive experience with GitHub and the GitHub workflow. A willingness to meet new members of the open source community.
* _Recommended:_ Experience in the open source community would be a positive, but it is not required.
* _Mentors:_ Matt Snell, Matt Germonprez, Saleh Abdel Motaal

# Microtasks

To become familiar with the CHAOSS D&I Badging Program, Please take a look at the following documentation:

  - [IMS Standards for Digital Badges](https://www.imsglobal.org/activity/digital-badges) (Emphasis on the Background section at the bottom of the page)
  - [The Journal of Open Source Software Submission Process](https://joss.readthedocs.io/en/latest/)
  - [A quick Overview of the CHAOSS Project](https://chaoss.community/about/)

Once you are more familiar with the related projects, Please complete these microtasks:

Any line marked with a `Q` contains a question you must answer.
Any line marked with an `A` contains an action you must take.

  - Microtask 0
  After reviewing the IMS Standards for Digital Badges and the Journal of Open Source Software Documentation, answer the following questions:
  `Q 0` How would IMS standards be helpful in creating improving the D&I Badging Project?
  `Q 1` What parts of the Journal of Open Source Software Documentation could be helpful in improving the D&I Badging Project? (Hint: There are no wrong answers)
  
  - Microtask 1:
  Navigate to [the D&I badging repository](https://github.com/Nebrethar/Docs-Diversity-Inclusion-Badging) and review both the Event and Project folders.
  `Q 2` How do these folders differ from each other?
  `Q 3` How are they similar?

  - Microtask 2:
  Review the issue templates, namely those used for submitting to the project. Clone the repository to your local computer and review the issue templates again.
  `Q 4` Are the issue templates any different when you view them in GitHub versus your local machine? If so, how?
  `Q 5` Explain why this project may want to use GitHub issue templates as a badging submission method.

**Comment by Nebrethar** [comment]
I have moved this issue to the new Badging organization, as we are moving everything here

**Comment by Nebrethar** [comment]
`
Hi @Nebrethar @GeorgLink! I am going through the links under 'Author and Reviewer Guides' in JOSS documentation. Are there any specific parts that should be focused more upon than the others?
`

_Originally posted by @bistaastha in https://github.com/Nebrethar/Docs-Diversity-Inclusion-Badging/issues/5#issuecomment-590787062_

Hi there! Thanks for the question. 

Right now, the most comprehensive part of our workflow is the submission process. If we need one aspect worked on more than anything else, it would be to create a detailed peer review process.

Possible working tasks related to JOSS Documentation include:
- Clearly defining submission requirements for both events and projects
- Defining the requirements and expectations of becoming a reviewer
- Creating a D&I adaption of the "Review checklist" outlines in JOSS documentation

I hope this helps! Let me know if you have further questions.

**Comment by bistaastha** [comment]
@Nebrethar This will help a lot. Thanks!

**Comment by bistaastha** [comment]
Hi! I have a small doubt. Does the term 'software badge' in `Q 0` refer to:
- A digital badge created using IMS standards, or
- A digital badge created using IMS standards which is associated with a software and has that particular software's metadata attached with it?

I think it is more likely the second point, but it's still a little confusing to me.

**Comment by SMotaal** [comment]
@Nebrethar If want to sync before our weekly meet, I’m on slack.

**Comment by SMotaal** [comment]
@Nebrethar I'm seeing double? https://github.com/Nebrethar/Docs-Diversity-Inclusion-Badging/issues/5

I'm just going to blockquote this one — let me know if that was not the intent!

If so, do we want to transfer it over on Sunday and reopen?

**Comment by Nebrethar** [comment]
> @Nebrethar I'm seeing double? [Nebrethar/Docs-Diversity-Inclusion-Badging#5](https://github.com/Nebrethar/Docs-Diversity-Inclusion-Badging/issues/5)
> 
> I'm just going to blockquote this one — let me know if that was not the intent!
> 
> If so, do we want to transfer it over on Sunday and reopen?

The original intent was to move the PR. I've already changed the link to this issue in the GSoC document 😄 That way we don't have people going to the old repository.

Edit: I'm going to remove BQ for now

**Comment by Nebrethar** [comment]
> Hi! I have a small doubt. Does the term 'software badge' in `Q 0` refer to:
> 
> * A digital badge created using IMS standards, or
> * A digital badge created using IMS standards which is associated with a software and has that particular software's metadata attached with it?
> 
> I think it is more likely the second point, but it's still a little confusing to me.

@bistaastha 

Thanks for another question 😄 I appreciate you interest in this project.

`Q0` is open ended to provoke discussion. I agree that it can also be seen as ambiguous. I have narrowed the scope.

The question has been changed from:
`How would IMS standards be helpful in creating a software badge?`
To be more like `Q1`:
`How would IMS standards be helpful in creating improving the D&I Badging Project?`

The header "**Specification Documents**" under the [IMS Standards Page](https://www.imsglobal.org/activity/digital-badges#digcredpublic) will probably be most useful.

And this is not required to be a long answer 😄 do your best to answer it in your own way. Thanks again and let me know if you run into any other issues

**Comment by bistaastha** [comment]
Thanks a lot @Nebrethar :grin:

**Comment by Mishrasubha** [comment]
Hi! This project strikes my interest would love to work on this, I will start off with the microtasks ASAP and update my progress here.

**Comment by bistaastha** [comment]
Hi all! I have worked on all the microtasks and my work is here: https://docs.google.com/document/d/1S75PolGiD5gUlXYcAN-XIatAk_r5RRIYvV3NcuwvTHA/edit?usp=sharing
Please review it and let me know how it can be improved :) I think I'll be simultaneously improving my microtask answers till the end of the application period along with working on the GSoC proposal. Is that okay or is it mandatory to wrap up the microtask first?

**Comment by thecraftman** [comment]
Good day all, I am interested in contributing to this project for the Outreachy program. I have worked on the microtasks and my PR can be found here [https://github.com/badging/diversity-and-inclusion/pull/3/commits/bc09855341e2909a8c3851092e2a39b14481ad1d](https://github.com/badging/diversity-and-inclusion/pull/3/commits/bc09855341e2909a8c3851092e2a39b14481ad1d) 

[https://github.com/badging/diversity-and-inclusion/pull/3](https://github.com/badging/diversity-and-inclusion/pull/3l)

 Please review, so that i can be able to improve it. Thanks :)

I am also working on my Outreachy Proposal

**Comment by tharun143** [comment]
This is Tharun Rvauri. I started contributing to CHAOSS on May 9th. 
I sent three patches and the three patches were merged. 

I found that CHAOSS org selected for GSOD. I am very happy to see it.
I went through the ideas list and found D&I badging project needs documentation.

I opened an issue in the Badging repo about the GSOD discussion and I got a quick response from Matt Snell.

In the meantime, I went through the project (Build workflow process for CHAOSS Diversity & Inclusion Program) working by Bistaastha and I found it interesting. 

I went through the Micro tasks and IMS standards found it very interesting how badging works. I will go through the general and will try to fill the microtasks.

I am looking forward to working with @Nebrethar and @bistaastha  

Stay safe and stay healthy :)

**Comment by Nebrethar** [comment]
Hi @tharun143 ! Thanks for checking out these microtasks.

We are working on new microtasks for the GSoD applications. This set of microtasks was actually intended for Google Summer of Code and Outreachy mentorships. I will still keep you updated when that shows up. It will be on the [meta](https://github.com/badging/meta) repository.

Thankfully it looks like we will have some overlap with these microtasks! If you want to track the reviews and changes as they happen, check out where I opened a PR for the new microtasks [here](https://github.com/badging/meta/pull/24). We won't take responses on the new microtasks until they are finished and put into an issue on the repo. We look forward to seeing your responses!
